name: Run detekt and
on: [pull_request]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v1
      with:
        java-version: 11
        architecture: x64
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Cache Gradle modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.OS }}-gradle-${{ hashFiles('./build.gradle.kts') }}
        restore-keys: |
          ${{ runner.OS }}-gradle-
          ${{ runner.OS }}-
    - run: yarn install
    - run: chmod a+x ./gradlew
    - run: ./gradlew detekt
    - run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: detekt-report
        path: build/reports/detekt.html
